---
title: "Analysis metabolomic data"
author: "Martino Bernasconi and Klaus Gröbner"
date: "30 3 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

load packages
```{r}
library(numbers)
library(SummarizedExperiment)
library(GenomicRanges)
library(dplyr)
library(ggplot2)
library(limma)
library(pheatmap)
```


loading the data
```{r}
setwd("C:/Users/klaus/Documents/ETH/FS_2021/Epi_MH") 
path <-"C:/Users/klaus/Documents/ETH/FS_2021/Epi_MH/"
meta<-read.csv("metadata.csv")
mapped<-read.csv("mapped_data.csv")

#we don't need the first column
mapped<-mapped[,-1]

#head(mapped)
head(meta)
```

prepare the path
```{r}
path <-"C:/Users/klaus/Documents/ETH/FS_2021/Epi_MH/"
```
Prepare the data
```{r}

#remove duplicate metabolites

dups<-duplicated(mapped$Top.annotation.name)
sum(dups)
mapped<-mapped[!dups,]

#rename .1 columns
colnames(mapped)<-sub(".1","",colnames(mapped),fixed=TRUE)
#head(mapped)


#create new matrix to store averaged data
uniqcols<-unique(colnames(mapped))
map<-matrix(data=NA,nrow=nrow(mapped),ncol = length(uniqcols))
colnames(map)<-uniqcols

#Fill said matrix up with the data
for (name in (uniqcols)){
  #temporarily store all the columns of one sample in a matrix
  temp<-as.matrix(mapped[,which(colnames(mapped)==name)])
  
  #if we don't have a duplicate we just take the sample
  if(ncol(temp)==1){
    map[,name]<-temp
  }
  
  #if we have duplicates we take the mean
  else{
     map[,name]<- rowMeans(temp)
  }
}

#str(map)

#set rownames to the metabolite names
map<-as.data.frame(map)
rownames(map)<-map$Top.annotation.name
map<-map[,-1]
#str(map)

```

prepare the metadata
```{r}
#delete all samples that we don't use
meta<-meta[meta$ï..Name %in% colnames(map),]
head(meta)

#order the mapped data in the same order as the metadata
map<-map[,order(colnames(map))]
identical(colnames(map),meta$ï..Name)
```

make the summarized experiment 
```{r}
#create logtransformed matrix

temp<-matrix(log(as.numeric(as.matrix(map))),ncol = ncol(map))
rownames(temp)<-rownames(map)
colnames(temp)<-colnames(map)
logmap<-as.data.frame(temp)



assay <- list(average=map, log=logmap)

#create the summarized experiment object

se<-SummarizedExperiment(assays =assay, colData=meta)

#save the object
save(se, file = "se_metabolomics.RData")
write.csv(logmap,"logmap.csv")

```

Quality control

create some boxplots
```{r}
#boxplot(t(se@assays@data[[2]]))

boxplot(se@assays@data[[2]], outline = FALSE,xlab="sample",ylab="level (log)",
        main="Boxplot of all samples")


```

make a density plot
```{r}

plotDensities(se@assays@data[[2]],legend="topright",
        main="Density plot of the samples", group = meta$Group)
```

PCA
```{r}
tlogmap<-t(se@assays@data[[2]])
dismat<-dist(tlogmap)
pcs<-prcomp(dismat)

#create a dataframe with the PCs

pcmap<-data.frame(pcs$x,se@colData$Housing,se@colData$Group,
                  se@colData$Timepoint, se@colData$Comb)

#create a plot with the PCA
ggplot(pcmap, aes(x=PC1, y=PC2, col=se.colData.Housing))+geom_point(size=2)+
  ggtitle("PC plot with Housing")
```

```{r}
ggplot(pcmap, aes(x=PC1, y=PC2, col=se.colData.Group))+geom_point(size=2)+
  ggtitle("PC plot with Group")
```
```{r}
ggplot(pcmap, aes(x=PC1, y=PC2, col=se.colData.Timepoint))+geom_point(size=2)+
  ggtitle("PC plot with Timepoint")
```

```{r}
ggplot(pcmap, aes(x=PC1, y=PC2, col=se.colData.Comb))+geom_point(size=2)+
  ggtitle("PC plot with Combination")
```

Create a heatmap of the metabolites

```{r, message=F, warning=F, fig.width=8, fig.height=8}

#calculate the variance for all the metabolites
DEMs <- apply(assays(se)[[2]],1,var)

#sort the vector with the variances and take the 500 with the most variance
top500 <- names(sort(DEMs, decreasing=T))[1:500]

#store the most variable metabolite data
top500DEMs <- assays(se)[[2]][top500,]



#create the heatmap
pheatmap(as.matrix(top500DEMs), show_rownames = FALSE, show_colnames = FALSE, annotation_col = as.data.frame(colData(se)[,c("Group", "Timepoint", "Housing", "Comb")]), annotation_names_col = FALSE)

```

start the modelling

```{r}

#define the correct baseline for each factor
levels(as.factor(se@colData$Housing))
se@colData$Housing<-relevel(as.factor(se@colData$Housing),"SH")
levels(as.factor(se@colData$Housing))
levels(as.factor(se@colData$Timepoint))
levels(as.factor(se@colData$Group))
levels(as.factor(se@colData$Number))
levels(as.factor(se@colData$Comb))

#create the full model matrix
mm<-model.matrix(~se@colData$Group*se@colData$Timepoint*se@colData$Housing, data = assays(se)[[2]])
#head(mm)

#extract all the wanted factors from the model matrix
mm<-mm[,c(1:4,6,7,9:12)]
head(mm)

#make the fit
fit<-eBayes(lmFit(se@assays@data@listData$log,mm))
#fit
#cat("coefficients\n\n")
#fit$coefficients
#cat("\n\npvalues\n\n")
#fit$p.value
res <- topTable(fit, n=Inf)
```

interpret the results. find significant values

```{r}
#extract all the p values and coefficients from the fit
pvals<-fit$p.value
coefs<-as.data.frame(fit$coefficients)

#Sort pvalues and print the most significant pvalues

for (i in (1:ncol(pvals))){
  temp<-pvals[order(pvals[,i],decreasing=FALSE),]
  print(colnames(pvals)[i])
  print(temp[(1:5),i])
 
}



```

Extract all the significant values
```{r}
cols<-colnames(mm)

#go through each factor, choose the significant values and potentially save them in a csv file
for (i in (1:length(cols))){
  res<-topTable(fit,coef=cols[i], n=Inf)

  res<-res[res$adj.P.Val<0.05,]
    #write.csv(res, paste0(path,"stats_model_meta/","Metabolites",cols[i],".csv"))
}
```






